### ISSUE TITLE
Lightning + Search API 1.0-beta5

### ISSUE THREAD

**Issue by sylus** [acquia/lightning#324]
Hi there! ^_^

My TravisCI build has suddenly failed and I noticed it was a result of Search API just releasing a new release.

My build is located here: https://travis-ci.org/drupalwxt/wxt/builds/217929831

The errors in particular can be found on this line: https://travis-ci.org/drupalwxt/wxt/builds/217929831#L718

I managed to correct my builds by specifying search_api @ 1.0-beta4 which doesn't have the problem and my build then subsequently passed: https://travis-ci.org/drupalwxt/wxt/builds/217935664

I was curious if anyone else is seeing this?

A subset of the log is given below:

```sh
(search_api) did not specify an instance class. in
/var/www/html/core/lib/Drupal/Component/Plugin/Factory/DefaultFactory.php:79
Stack trace:
#0
/var/www/html/core/lib/Drupal/Core/Plugin/Factory/ContainerFactory.php(17):
Drupal\Component\Plugin\Factory\DefaultFactory::getPluginClass('search_api',
Array, 'Drupal\\views\\Pl...')
#1
/var/www/html/core/lib/Drupal/Component/Plugin/PluginManagerBase.php(84):
Drupal\Core\Plugin\Factory\ContainerFactory->createInstance('search_api',
Array)
#2
/var/www/html/core/modules/views/src/Plugin/views/display/DisplayPluginBase.php(810):
Drupal\Component\Plugin\PluginManagerBase->createInstance('search_api')
#3
/var/www/html/core/modules/views/src/Plugin/views/display/DisplayPluginBase.php(933):
Drupal\views\Plugin\views\display\DisplayPluginBase->getPlugin('cache')
#4
/var/www/html/core/modules/views/src/Plugin/views/display/DisplayPluginBase.php(952):
Drupal\views\Plugin\views\display\DisplayPluginBase->getAllPlugins(true)
#5
/var/www/html/core/lib/Drupal/Core/Plugin/PluginDependencyTrait.php(35):
Drupal\views\Plugin\views\display\DisplayPluginBase->calculateDependencies()
#6 /var/www/html/core/modules/views/src/Entity/View.php(281):
Drupal\Core\Config\Entity\ConfigEntityBase->calculatePluginDependencies(Object(Drupal\views\Plugin\views\display\DefaultDisplay))
#7
/var/www/html/core/lib/Drupal/Core/Config/Entity/ConfigEntityBase.php(346):
Drupal\views\Entity\View->calculateDependencies()
#8 /var/www/html/core/modules/views/src/Entity/View.php(291):
Drupal\Core\Config\Entity\ConfigEntityBase->preSave(Object(Drupal\Core\Config\Entity\ConfigEntityStorage))
#9
/var/www/html/core/lib/Drupal/Core/Entity/EntityStorageBase.php(434):
Drupal\views\Entity\View->preSave(Object(Drupal\Core\Config\Entity\ConfigEntityStorage))
#10
/var/www/html/core/lib/Drupal/Core/Entity/EntityStorageBase.php(389):
Drupal\Core\Entity\EntityStorageBase->doPreSave(Object(Drupal\views\Entity\View))
#11
/var/www/html/core/lib/Drupal/Core/Config/Entity/ConfigEntityStorage.php(259):
Drupal\Core\Entity\EntityStorageBase->save(Object(Drupal\views\Entity\View))
#12 /var/www/html/core/lib/Drupal/Core/Entity/Entity.php(364):
Drupal\Core\Config\Entity\ConfigEntityStorage->save(Object(Drupal\views\Entity\View))
#13
/var/www/html/core/lib/Drupal/Core/Config/Entity/ConfigEntityBase.php(637):
Drupal\Core\Entity\Entity->save()
#14
/var/www/html/core/lib/Drupal/Core/Config/ConfigInstaller.php(337):
Drupal\Core\Config\Entity\ConfigEntityBase->save()
#15
/var/www/html/core/lib/Drupal/Core/Config/ConfigInstaller.php(141):
Drupal\Core\Config\ConfigInstaller->createConfiguration('', Array)
#16
/var/www/html/core/lib/Drupal/Core/ProxyClass/Config/ConfigInstaller.php(75):
Drupal\Core\Config\ConfigInstaller->installDefaultConfig('module',
'lightning_searc...')
```

**Comment by phenaproxima** [comment]
Hey there -- we are aware of the problem and I'm actually working on a fix right now, as I write this. A PR will be filed (and hopefully merged) by the end of the day. Cheers!

**Comment by sylus** [comment]
Ah thank you so much @phenaproxima for always being on top of these things; it is amazing and greatly appreciated!

Will leave this issue open for right now ^_^

**Comment by phenaproxima** [comment]
No problem. This will give me an issue to file the PR against, for documentation purposes. So thank YOU!

**Comment by phenaproxima** [comment]
Pull request filed, so I'm closing this.
