### ISSUE TITLE
Fresh install: 'The "list" plugin does not exist.'

### ISSUE THREAD

**Issue by kylebrowning** [acquia/lightning#455]
Full error below

```exception 'Drupal\Component\Plugin\Exception\PluginNotFoundException' with message 'The "list" plugin does not exist.' in                                                            [error]
/var/www/league-cms/docroot/core/lib/Drupal/Component/Plugin/Discovery/DiscoveryTrait.php:52
Stack trace:
#0 /var/www/league-cms/docroot/core/lib/Drupal/Component/Plugin/Discovery/DiscoveryCachedTrait.php(25): Drupal\Core\Plugin\DefaultPluginManager->doGetDefinition(Array, 'list', true)
#1 /var/www/league-cms/docroot/core/lib/Drupal/Core/TypedData/TypedDataManager.php(78): Drupal\Core\Plugin\DefaultPluginManager->getDefinition('list')
#2 /var/www/league-cms/docroot/core/lib/Drupal/Core/TypedData/TypedDataManager.php(104): Drupal\Core\TypedData\TypedDataManager->createInstance('list', Array)
#3 /var/www/league-cms/docroot/core/lib/Drupal/Core/TypedData/TypedDataManager.php(187):
Drupal\Core\TypedData\TypedDataManager->create(Object(Drupal\Core\Field\BaseFieldDefinition), NULL, 'langcode', Object(Drupal\Core\Entity\Plugin\DataType\EntityAdapter))
#4 /var/www/league-cms/docroot/core/lib/Drupal/Core/Field/FieldTypePluginManager.php(74):
Drupal\Core\TypedData\TypedDataManager->getPropertyInstance(Object(Drupal\Core\Entity\Plugin\DataType\EntityAdapter), 'langcode', NULL)
#5 /var/www/league-cms/docroot/core/lib/Drupal/Core/Entity/ContentEntityBase.php(526): Drupal\Core\Field\FieldTypePluginManager->createFieldItemList(Object(Drupal\user\Entity\User),
'langcode', NULL)
#6 /var/www/league-cms/docroot/core/lib/Drupal/Core/Entity/ContentEntityBase.php(490): Drupal\Core\Entity\ContentEntityBase->getTranslatedField('langcode', 'x-default')
#7 /var/www/league-cms/docroot/core/lib/Drupal/Core/Entity/ContentEntityBase.php(666): Drupal\Core\Entity\ContentEntityBase->get('langcode')
#8 /var/www/league-cms/docroot/core/lib/Drupal/Core/Entity/ContentEntityBase.php(222): Drupal\Core\Entity\ContentEntityBase->setDefaultLangcode()
#9 /var/www/league-cms/docroot/core/lib/Drupal/Core/Entity/ContentEntityStorageBase.php(87): Drupal\Core\Entity\ContentEntityBase->__construct(Array, 'user', false)
#10 /var/www/league-cms/docroot/core/lib/Drupal/Core/Entity/EntityStorageBase.php(184): Drupal\Core\Entity\ContentEntityStorageBase->doCreate(Array)
#11 /var/www/league-cms/docroot/core/modules/user/user.install(74): Drupal\Core\Entity\EntityStorageBase->create(Array)
#12 [internal function]: user_install()
#13 /var/www/league-cms/docroot/core/lib/Drupal/Core/Extension/ModuleHandler.php(391): call_user_func_array('user_install', Array)
#14 /var/www/league-cms/docroot/core/lib/Drupal/Core/Extension/ModuleInstaller.php(287): Drupal\Core\Extension\ModuleHandler->invoke('user', 'install')
#15 /var/www/league-cms/docroot/core/lib/Drupal/Core/ProxyClass/Extension/ModuleInstaller.php(83): Drupal\Core\Extension\ModuleInstaller->install(Array, false)
#16 /var/www/league-cms/docroot/core/includes/install.core.inc(1078): Drupal\Core\ProxyClass\Extension\ModuleInstaller->install(Array, false)
#17 /var/www/league-cms/docroot/core/includes/install.core.inc(668): install_base_system(Array)
#18 /var/www/league-cms/docroot/core/includes/install.core.inc(546): install_run_task(Array, Array)
#19 /var/www/league-cms/docroot/core/includes/install.core.inc(117): install_run_tasks(Array)
#20 /var/www/league-cms/vendor/drush/drush/includes/drush.inc(726): install_drupal(Object(Composer\Autoload\ClassLoader), Array)
#21 /var/www/league-cms/vendor/drush/drush/includes/drush.inc(711): drush_call_user_func_array('install_drupal', Array)
#22 /var/www/league-cms/vendor/drush/drush/commands/core/drupal/site_install.inc(82): drush_op('install_drupal', Object(Composer\Autoload\ClassLoader), Array)
#23 /var/www/league-cms/vendor/drush/drush/commands/core/site_install.drush.inc(255): drush_core_site_install_version('lightning', Array)
#24 [internal function]: drush_core_site_install('lightning', 'install_configu...', 'install_configu...')
#25 /var/www/league-cms/vendor/drush/drush/includes/command.inc(422): call_user_func_array('drush_core_site...', Array)
#26 /var/www/league-cms/vendor/drush/drush/includes/command.inc(231): _drush_invoke_hooks(Array, Array)
#27 [internal function]: drush_command('lightning', 'install_configu...', 'install_configu...')
#28 /var/www/league-cms/vendor/drush/drush/includes/command.inc(199): call_user_func_array('drush_command', Array)
#29 /var/www/league-cms/vendor/drush/drush/lib/Drush/Boot/BaseBoot.php(67): drush_dispatch(Array)
#30 /var/www/league-cms/vendor/drush/drush/includes/preflight.inc(66): Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#31 /var/www/league-cms/vendor/drush/drush/drush.php(12): drush_main()
#32 {main}
```

Cant seem to get a fresh install of drupal with lightning, using standard profile works fine though.

Any thoughts?

**Comment by balsama** [comment]
Hm. How did you build your codebase or what tarball did you download to start with?

**Comment by kylebrowning** [comment]
BLT.

**Comment by balsama** [comment]
and List is a plugin provided by the User module?? I have no clue.

The drupal composer packagist was down for a bit today too. Any chance your codebase wasn't built properly?

**Comment by kylebrowning** [comment]
I built this on Friday, nuked the vendor and composer.lock this morning to try again.

Just did that process again, and same issue.

```
{
    "name": "acquia/blt-project",
    "description": "Project template for Drupal 8 sites built with BLT.",
    "type": "project",
    "minimum-stability": "dev",
    "prefer-stable": true,
    "require": {
        "acquia/blt": "^8.3",
        "geerlingguy/drupal-vm": "~4.3"
    },
    "require-dev": {},
    "extra": {
        "enable-patching": true,
        "installer-paths": {
            "docroot/core": [
                "type:drupal-core"
            ],
            "docroot/modules/contrib/{$name}": [
                "type:drupal-module"
            ],
            "docroot/modules/custom/{$name}": [
                "type:drupal-custom-module"
            ],
            "docroot/profiles/contrib/{$name}": [
                "type:drupal-profile"
            ],
            "docroot/profiles/custom/{$name}": [
                "type:drupal-custom-profile"
            ],
            "docroot/themes/contrib/{$name}": [
                "type:drupal-theme"
            ],
            "docroot/themes/custom/{$name}": [
                "type:drupal-custom-theme"
            ],
            "docroot/libraries/{$name}": [
                "type:drupal-library"
            ],
            "drush/contrib/{$name}": [
                "type:drupal-drush"
            ]
        },
        "merge-plugin": {
            "require": [
                "vendor/acquia/blt/composer.required.json",
                "vendor/acquia/blt/composer.suggested.json"
            ],
            "include": [
                "blt/composer.overrides.json"
            ],
            "merge-extra": true,
            "merge-extra-deep": true,
            "merge-scripts": true,
            "replace": false,
            "ignore-duplicates": true
        }
    }
}

```

**Comment by balsama** [comment]
I'm sure CI would have caught this, but I spun up a test last night to verify. I can't reproduce this with a fresh build of BLT project.

**Comment by kylebrowning** [comment]
Are you using Drupal Vm or just local LAMP?

**Comment by balsama** [comment]
I was just using a local LAMP stack and called drush si directly.

**Comment by kylebrowning** [comment]
Do believe this is either a DrupalVM or composer issue.

**Comment by grahl** [comment]
Encountering something similar, I think this ist the cause https://github.com/geerlingguy/drupal-vm/issues/1547
