### ISSUE TITLE
Routes not created on Lightning and Drush 

### ISSUE THREAD

**Issue by rotari** [acquia/lightning#476]
Steps to reproduce:
 - drush site-install
 - drush en content_translation

Error retuned:
```
exception 'Symfony\Component\Routing\Exception\RouteNotFoundException' with message 'Route                       [error]
"entity.configurable_language.collection" does not exist.' in
\docroot\core\lib\Drupal\Core\Routing\RouteProvider.php:190
Stack trace:
#0 \docroot\core\lib\Drupal\Core\Routing\UrlGenerator.php(419):
Drupal\Core\Routing\RouteProvider->getRouteByName('entity.configur...')
#1 \docroot\core\lib\Drupal\Core\Routing\UrlGenerator.php(269):
Drupal\Core\Routing\UrlGenerator->getRoute('entity.configur...')
#2 \docroot\core\lib\Drupal\Core\Render\MetadataBubblingUrlGenerator.php(105):
Drupal\Core\Routing\UrlGenerator->generateFromRoute('entity.configur...', Array, Array, true)
#3 \docroot\core\lib\Drupal\Core\Url.php(753):
Drupal\Core\Render\MetadataBubblingUrlGenerator->generateFromRoute('entity.configur...', Array, Array, false)
#4 \docroot\core\modules\content_translation\content_translation.install(21):
Drupal\Core\Url->toString()
#5 [internal function]: content_translation_install()
#6 \docroot\core\lib\Drupal\Core\Extension\ModuleHandler.php(391):
call_user_func_array('content_transla...', Array)
#7 \docroot\core\lib\Drupal\Core\Extension\ModuleInstaller.php(287):
Drupal\Core\Extension\ModuleHandler->invoke('content_transla...', 'install')
#8 \docroot\core\lib\Drupal\Core\ProxyClass\Extension\ModuleInstaller.php(83):
Drupal\Core\Extension\ModuleInstaller->install(Array, true)
#9 )\Acquia\tools\vendor\drush\drush\commands\core\drupal\environment.inc(131):
Drupal\Core\ProxyClass\Extension\ModuleInstaller->install(Array, true)
#10 \Acquia\tools\vendor\drush\drush\commands\core\drupal\environment.inc(198):
drush_module_install(Array)
#11 \Acquia\tools\vendor\drush\drush\commands\pm\pm.drush.inc(1167):
drush_module_enable(Array)
#12 [internal function]: drush_pm_enable('content_transla...')
#13 \Acquia\tools\vendor\drush\drush\includes\command.inc(422):
call_user_func_array('drush_pm_enable', Array)
#14 \Acquia\tools\vendor\drush\drush\includes\command.inc(231):
_drush_invoke_hooks(Array, Array)
#15 [internal function]: drush_command('content_transla...')
#16 Acquia\tools\vendor\drush\drush\includes\command.inc(199):
call_user_func_array('drush_command', Array)
#17 Acquia\tools\vendor\drush\drush\lib\Drush\Boot\BaseBoot.php(67):
drush_dispatch(Array)
#18 Acquia\tools\vendor\drush\drush\includes\preflight.inc(66):
Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#19 Acquia\tools\vendor\drush\drush\drush.php(12): drush_main()
#20 {main}
```

PHP 5.6.30
Drupal 8.3.7 
Drush 8.1.10

A quick solution would be to rebuild the routes in language module but the source of the issue seems to be somewhere else
```
function language_install(){
  $router_builder = \Drupal::service('router.builder');
  $router_builder->rebuild();
}
```

**Comment by phenaproxima** [comment]
Using Drush 9, I confirmed that this happens on Lightning, but _not_ vanilla Drupal. That's maddening. I have no idea, off the top of my head, what could be causing this wonkiness.

So, once more unto the breach.

**Comment by phenaproxima** [comment]
I spent hours tracing this and figured out what's happening.

First, this is unambiguously a bug in core. It's an extremely sneaky bug that would only happen under very specific conditions, but it is a core bug. I intend to file a core issue later with a failing test (working on that for the rest of the day).

The problem is actually triggered by the JSON API module, which is one of Content API's dependencies. For reasons too complex to go into, it causes the URL generator service to have a stale route provider by the time Content Translation is installed, which breaks the URL generation being done in content_translation_install().

The easiest workaround, at the moment, is to install content_translation and language in two separate commands:

```
$ drush en language
$ drush en content_translation
```

If you do this, you will bypass the bug.

**Comment by phenaproxima** [comment]
I have filed a core issue with a fail patch to prove that the fix, whatever it will be, works. https://www.drupal.org/node/2913912
